### ISSUE TITLE
Nil reference parsing empty list items

### ISSUE THREAD

**Issue by chronodm** [dmarcotte/github-markdown-preview#41]
Steps to reproduce:
- Create Markdown document containing a list with an empty item, e.g.

```
-
```

- Preview the document

Expected:
- Document previews correctly

Actual:
- `github-markdown-preview` exits with the stack trace below:

```
$ /Users/dmoles/.rvm/gems/ruby-2.2.2/gems/github-markdown-preview-4.0.0/lib/github-markdown-preview/filter/task_list_filter.rb:30:in `block in call': undefined method `text?' for nil:NilClass (NoMethodError)
	from /Users/dmoles/.rvm/gems/ruby-2.2.2/gems/nokogiri-1.6.5/lib/nokogiri/xml/node_set.rb:237:in `block in each'
	from /Users/dmoles/.rvm/gems/ruby-2.2.2/gems/nokogiri-1.6.5/lib/nokogiri/xml/node_set.rb:236:in `upto'
	from /Users/dmoles/.rvm/gems/ruby-2.2.2/gems/nokogiri-1.6.5/lib/nokogiri/xml/node_set.rb:236:in `each'
	from /Users/dmoles/.rvm/gems/ruby-2.2.2/gems/github-markdown-preview-4.0.0/lib/github-markdown-preview/filter/task_list_filter.rb:38:in `call'
	from /Users/dmoles/.rvm/gems/ruby-2.2.2/gems/html-pipeline-2.0/lib/html/pipeline/filter.rb:130:in `call'
	from /Users/dmoles/.rvm/gems/ruby-2.2.2/gems/html-pipeline-2.0/lib/html/pipeline.rb:121:in `block in perform_filter'
	from /Users/dmoles/.rvm/gems/ruby-2.2.2/gems/html-pipeline-2.0/lib/html/pipeline.rb:159:in `instrument'
	from /Users/dmoles/.rvm/gems/ruby-2.2.2/gems/html-pipeline-2.0/lib/html/pipeline.rb:120:in `perform_filter'
	from /Users/dmoles/.rvm/gems/ruby-2.2.2/gems/html-pipeline-2.0/lib/html/pipeline.rb:106:in `block (2 levels) in call'
	from /Users/dmoles/.rvm/gems/ruby-2.2.2/gems/html-pipeline-2.0/lib/html/pipeline.rb:105:in `each'
	from /Users/dmoles/.rvm/gems/ruby-2.2.2/gems/html-pipeline-2.0/lib/html/pipeline.rb:105:in `inject'
	from /Users/dmoles/.rvm/gems/ruby-2.2.2/gems/html-pipeline-2.0/lib/html/pipeline.rb:105:in `block in call'
	from /Users/dmoles/.rvm/gems/ruby-2.2.2/gems/html-pipeline-2.0/lib/html/pipeline.rb:159:in `instrument'
	from /Users/dmoles/.rvm/gems/ruby-2.2.2/gems/html-pipeline-2.0/lib/html/pipeline.rb:103:in `call'
	from /Users/dmoles/.rvm/gems/ruby-2.2.2/gems/github-markdown-preview-4.0.0/lib/github-markdown-preview/html_preview.rb:96:in `update'
	from /Users/dmoles/.rvm/gems/ruby-2.2.2/gems/github-markdown-preview-4.0.0/lib/github-markdown-preview/html_preview.rb:44:in `initialize'
	from /Users/dmoles/.rvm/gems/ruby-2.2.2/gems/github-markdown-preview-4.0.0/bin/github-markdown-preview:31:in `new'
	from /Users/dmoles/.rvm/gems/ruby-2.2.2/gems/github-markdown-preview-4.0.0/bin/github-markdown-preview:31:in `<top (required)>'
	from /Users/dmoles/.rvm/gems/ruby-2.2.2/bin/github-markdown-preview:23:in `load'
	from /Users/dmoles/.rvm/gems/ruby-2.2.2/bin/github-markdown-preview:23:in `<main>'
	from /Users/dmoles/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/dmoles/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by dmarcotte** [comment]
Closed in #42.
